# Amphi 3 - Useful libraries in Python for Numeric Computation and Data Processing

# 1. Numpy

## 1.1 numpy arrays (numpy.ndarray)

A numpy ndarray (numpy array) can represent a list of list of list ... of numbers or str.
It implements methods for basic operation on vectors and matrices, hence usually used in linear algebra problems.

A numpy array composed of a list or tuple of $k$ numbers or str is said of **ndim** 1 and of **shape** ($k$). In this case we say that the list or tuple is also of **ndim** 1 and **shape** ($k$).

In [2]:
import numpy as np
A = np.array([1, 2, 3])
print(A)
print(A.ndim)
print(A.shape)
print(type(A))

[1 2 3]
1
(3L,)
<type 'numpy.ndarray'>


Recursively, a numpy array composed of a list/tuple/numpy array of $k$ lists/tuples/numpy arrays, each of which is of **ndim** $n-1$ and **shape** ($k_1, k_2, \ldots, k_{n-1}$) is said to be of **ndim** $n$ and **shape** ($k, k_1, k_2, \ldots, k_{n-1}$).

In [42]:
B = np.array([[1, 2, 3], [3, 4, 5]])
print(B)
print(B.ndim)
print(B.shape)

[[1 2 3]
 [3 4 5]]
2
(2L, 3L)


In [43]:
C = np.array([[[1, 2, 3]]])
print(C)
print(C.ndim)
print(C.shape)

[[[1 2 3]]]
3
(1L, 1L, 3L)


By convention, a scalar (number of string) can also form a numpy array. Its **ndim** is 0 and its **shape** is ().

In [51]:
N = np.array(1)
print(N.ndim)
print(N.shape)

0
()


We can use numpy arrays of **ndim** 1 to represent vectors and numpy arrays of **ndum** 2 to represent matrices.

We can access and modify elements in a numpy array. Numpy arrays are mutable.

In [70]:
B = np.array([[1, 2, 3], [3, 4, 5]])
print("Get the first row")
print(B[0])
print("Get the first element of the first row")
print(B[0, 0]) #instead of B[0][0]
print("Get the second column")
print(B[:, 1])
print("Modify the second column to 100, 200")
B[:, 1] = [100, 200]
print("The array after modification")
print(B)

Get the first row
[1 2 3]
Get the first element of the first row
1
Get the second column
[2 4]
Modify the second column to 100, 200
The array after modification
[[  1 100   3]
 [  3 200   5]]


We can also access elements of arrays using list.

In [49]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
B = A**2
print(B[[1, 3, 5, 7, 9]])

#A = np.array([[1, 2], [3, 4]])
#print(A[[0, 1]] )
#print(A[[0, 1], [1, 1]] ) #print(A[[0, 1], 1] )

[ 1  9 25 49 81]


## 1.2 Operations on numpy arrays of the same shape

If two numpy arrays are of the same shape, their operations are elementwise.

In [68]:
B = np.array([[1, 2, 3], [3, 4, 5]])
D = np.array([[2, -1, 1], [2, -0, 3]])
print("B")
print(B)
print("D")
print(D)
print("B + D = ")
print(B + D)
print("B - D = ")
print(B - D)
print("B * D = ")
print(B * D)
print("sin(B) = ")
print(np.sin(B))

B
[[1 2 3]
 [3 4 5]]
D
[[ 2 -1  1]
 [ 2  0  3]]
B + D = 
[[3 1 4]
 [5 4 8]]
B - D = 
[[-1  3  2]
 [ 1  4  2]]
B * D = 
[[ 2 -2  3]
 [ 6  0 15]]
sin(B) = 
[[ 0.84147098  0.90929743  0.14112001]
 [ 0.14112001 -0.7568025  -0.95892427]]


## 1.3 Broadcasting in numpy arrays

Binary operations between a numpy array and a list or tuple of the same shape can be performed. Lists, tuples will be broadcasted into numpy arrays.

In [55]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = [(1, 2, 3), [4, 5, 6]]
A + B

array([[ 2,  4,  6],
       [ 8, 10, 12]])

If the arrays are not compatible in shape, binary operations cannot be applied. (the notion "compatibility in shape" will be described below)

In [57]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2, 3], [3, 4, 6]])
print(A.shape)
print(B.shape)
try:
    print(A + B)
except Exception as e:
    print(e)

(2L, 2L)
(2L, 3L)
operands could not be broadcast together with shapes (2,2) (2,3) 


Two arrays $A$ of shape $(a_{d_A}, \ldots,a_2, a_1)$ and $B$ of shape $(b_{d_B}, \ldots, b_2, b_1)$ are compatible in shape if $a_i = b_i$ or $a_i = 1$ or $b_i = 1$ for all $i = 1, \ldots, \min(d_A, d_B)$.

Examples of compatible-in-shape numpy-arrays:

Operations on compatible-in-shape numpy-arrays can be performed by duplicating every lists at level $i$ to $b_i$ copies where $a_i = 1$ or $i < \min(d_A, d_B)$ and vice versa.

In [61]:
A = np.array([1, 1])
B = np.array([[1, 2], [3, 4]])
print(A.shape)
print(B.shape)
print("---------Method1---------")
print(A + B)
print("---------Method2---------")
AA = np.array([[1, 1], [1, 1]])
print(AA + B)
print("---------Method3---------")
print(1 + B)

(2L,)
(2L, 2L)
---------Method1---------
[[2 3]
 [4 5]]
---------Method2---------
[[2 3]
 [4 5]]
---------Method3---------
[[2 3]
 [4 5]]


## 1.4. numpy.dot

The method **dot** in numpy is constructed to compute matrix multiplication and vector dot product. Do not consider it as a binary operation (do not apply it pointwisely).

If $A$ is of shape $(a_{d_A}, \ldots,a_2, a_1)$ and $B$ of shape $(b_{d_B}, \ldots, b_2, b_1)$, then **numpy.dot(A, B)** is defined if 
- $a_1 = b_2$
- or $d_B = 1$ and $a_1 = b_1$

In the first case, **numpy.dot(A, B)** is an array $C$ of shape $(a_{d_A}, \ldots, a_3, a_2, b_{d_B}, b_3, b_1)$, and:
$$
C[\dots, i, \ldots, j] = \sum(  A[\ldots, i, :] * B[ \ldots, :, j] )
$$

In [87]:
A = np.array([ [[1, 2, 3], [4, 5, 6]], [[0, 2, 0], [1, 0, 2]] ])
#print(A)
print(A.shape)
B = np.array([ [[1, 2], [2, 3], [3, 2]], [[1, 1], [1, 2], [2, 1]], [[2, 1], [0, 2], [1, 0]] ])
#print(B)
print(B.shape)
C = np.dot(A, B)
print("Shape of A*B")
print(C.shape)

#print(C)
#print(C[0,0,0,0])
#print(sum(A[0,0,:] * B[0,:,0]))

(2L, 2L, 3L)
(3L, 3L, 2L)
Shape of A*B
(2L, 2L, 3L, 2L)


In the second case, **numpy.dot(A, B)** is an array $C$ of shape $(a_{d_A}, \ldots, a_3, a_2)$, and:
$$
C[\dots, i, j] = \sum(  A[\ldots, i, :] * B )
$$

In [88]:
A = np.array([ [[1, 2, 3], [4, 5, 6]], [[0, 2, 0], [1, 0, 2]] ])
B = [1, 2, 3]
print(A)
print(B)
print("A.B = ")
print(A.dot(B))

[[[1 2 3]
  [4 5 6]]

 [[0 2 0]
  [1 0 2]]]
[1, 2, 3]
A.B = 
[[14 32]
 [ 4  7]]
[[[ 5 10 15]
  [20 25 30]]

 [[ 0 10  0]
  [ 5  0 10]]]


Corollary:
- If $A, B$ are vectors: **numpy.dot** returns the dot product
- If $A$ is matrix, $B$ is vector, it returns $AB$.
- If $A, B$ are matrices, it returns $AB$.
- If $A$ is vector, $B$ is matrix, it returns $A^t B$.

In [97]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[2, 3], [1, 2], [2, 2]])
v = np.array([1, 2, 5])
print("Matrix dot matrix")
print(A.dot(B))
print("Matrix dot vector")
print(A.dot(v))
print("Vector dot vector")
print(v.dot(v))
print("Vector dot matrix")
print(v.dot(B))

Matrix dot matrix
[[10 13]
 [25 34]]
Matrix dot vector
[20 44]
Vector dot vector
30
Vector dot matrix
[14 17]


If we want to compute $vv^t$, where $v$ is a vector?

In [101]:
v = np.array([1, 2, 5])
print(v.reshape(3,1).dot(v.reshape(1, 3)))

[[ 1  2  5]
 [ 2  4 10]
 [ 5 10 25]]


## 1.5. Linear Algebra: Vectors and Matrices

**Zero vector**

In [102]:
O = np.zeros(3)
O

array([ 0.,  0.,  0.])

**Zero matrices**

In [105]:
O = np.zeros((3, 4))
O

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**Identity matrix**


In [108]:
I = np.eye(5)
4 * I

array([[ 4.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  4.]])

**Diagonal matrix**

In [111]:
D = np.diag([2, 3, 4, 5])
D

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

**Transpose**

In [115]:
A = np.array([[1, 2], [3, 4]])
A.transpose()
#A.T

array([[1, 3],
       [2, 4]])

**Inverse**

In [117]:
A = np.array([[1, 2], [3, 4]])
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Determinant**

In [119]:
A = np.array([[1, 2], [3, 4]])
np.linalg.det(A)

-2.0000000000000004

**SVD**

In [121]:
A = np.array([[1, 2], [3, 4]])
U, S, V = np.linalg.svd(A)
U, S, V

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([ 5.4649857 ,  0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

**Diagonalisation**

In [125]:
A = np.array([[1, 2], [3, 4]])
Eigs = np.linalg.eig(A)
Eigs
#print(A.dot(Eigs[1]) - Eigs[0]*Eigs[1])

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

## 1.6 numpy.matrix

If we are interested in matrices (numpy-array of **ndim** 2 only), we can use **numpy.matrix**. **numpy.matrix** is a subclass of **numpy.array**, hence inherits attributes and methods of numpy-arrays.

Using **numpy.matrix** the **\*** operation performs matrix multiplication (not elementwise multiplication). 

In [4]:
M = np.matrix("1 2.5; 3 0.5")
N = np.matrix([[-1, 2], [0, -1]])
print(M)
print(N)
print(type(M), type(N))
print(M*N)
print(2*M)

[[ 1.   2.5]
 [ 3.   0.5]]
[[-1  2]
 [ 0 -1]]
(<class 'numpy.matrixlib.defmatrix.matrix'>, <class 'numpy.matrixlib.defmatrix.matrix'>)
[[-1.  -0.5]
 [-3.   5.5]]
[[ 2.  5.]
 [ 6.  1.]]


Operations between a matrix and an array return a matrix.

In [6]:
M = np.matrix("1 2.5; 3 0.5")
N = np.matrix([[-1, 2], [0, -1]])
print(type(M), type(N))
print(M*N)
print(type(M*N))

(<class 'numpy.matrixlib.defmatrix.matrix'>, <class 'numpy.matrixlib.defmatrix.matrix'>)
[[-1.  -0.5]
 [-3.   5.5]]
<class 'numpy.matrixlib.defmatrix.matrix'>


**Operations on matrices**

In [11]:
M = np.matrix("1 2.5; 3 0.5")
print("Inverse")
print(np.linalg.inv(M))
print("SVD")
print(np.linalg.svd(M))
print("Diagonalization")
print(np.linalg.eig(M))

Inverse
[[-0.07142857  0.35714286]
 [ 0.42857143 -0.14285714]]
SVD
(matrix([[-0.62087063, -0.78391305],
        [-0.78391305,  0.62087063]]), array([ 3.55190967,  1.97077084]), matrix([[-0.83690466, -0.54734869],
        [ 0.54734869, -0.83690466]]))
Diagonalization
(array([ 3.5, -2. ]), matrix([[ 0.70710678, -0.6401844 ],
        [ 0.70710678,  0.76822128]]))


**Attention:** If we want to multiply a numpy.matrix with a vector, the vector must be represented as a matrix or must be reshaped. The result is a numpy.matrix.

In [25]:
M = np.matrix("1 2.5; 3 0.5")
v = np.array([1, 2])
v = v.reshape(2, 1)
print(M*v)

[[ 6.]
 [ 4.]]


## 1.7 Other options

We can get a uniform partition on any $[a, b]$ segment by using **arange** or **linspace** methods. **arange** requires the mesh  (length of each subinterval) while **linspace** requires the number of points as an argument.

Attention: **arange(a, b, something)** does not contains **b**, while **linspace** does.

In [126]:
a = np.arange(1, 5, 0.1)
print(a)

[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4
  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9]


In [15]:
b = np.linspace(1, 5, 41)
print(b)

[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4
  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5. ]


We can reshape an array using **reshape** method.

In [21]:
A = np.array(range(1, 101))
print("Reshape to matrix 10x10")
B = A.reshape(10, 10)
print(B)
print("Reshape to 3d array 2x5x10")
C = A.reshape(2, 5, 10)
print(C)

Reshape to matrix 10x10
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
Reshape to 3d array 2x5x10
[[[  1   2   3   4   5   6   7   8   9  10]
  [ 11  12  13  14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27  28  29  30]
  [ 31  32  33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70]
  [ 71  72  73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97  98  99 100]]]


**flatten** is used to reshape nd-arrays to 1d-array.

In [26]:
A = np.array(range(1, 101))
B = A.reshape(10, 10)
print(B.flatten())

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


We can combine ndarrays horizontally or vertically by **vstack** and **hstack**.

In [30]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.vstack((A, B)))
print(np.hstack((A, B)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# 2. Scipy