## Data representation

### Read file

In [1]:
FILE_LOCATION = 'train.csv'

myFile = open(FILE_LOCATION)
content = myFile.read()
content[:1000]

'Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice\n1,60,RL,65,8450,Pave,NA,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196,Gd,TA,P

### Read line by line

In [2]:
myFile = open(FILE_LOCATION)
myFile.readlines()[:3]

['Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice\n',
 '1,60,RL,65,8450,Pave,NA,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196,G

### Read as dataframe

In [3]:
import pandas as pd

df = pd.read_csv(FILE_LOCATION, sep=',')
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
3         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
4         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

## Service 1: Find some houses based on some criteria

In [4]:
set(df['Neighborhood'].values)

{'Blmngtn',
 'Blueste',
 'BrDale',
 'BrkSide',
 'ClearCr',
 'CollgCr',
 'Crawfor',
 'Edwards',
 'Gilbert',
 'IDOTRR',
 'MeadowV',
 'Mitchel',
 'NAmes',
 'NPkVill',
 'NWAmes',
 'NoRidge',
 'NridgHt',
 'OldTown',
 'SWISU',
 'Sawyer',
 'SawyerW',
 'Somerst',
 'StoneBr',
 'Timber',
 'Veenker'}

In [5]:
def find(criterion):
    df = pd.read_csv(FILE_LOCATION, sep=',')
    results = []
    for idx, house in df.iterrows():
        kept = True
        record = [house['Id']]
        for k, V in criterion.items():
            if house[k] != V:
                kept = False
            else:
                record.append(V)
        if kept:
            results.append(record)
    return results

find({'Neighborhood': 'Blueste', 'Street': 'Pave'})

[[600, 'Blueste', 'Pave'], [957, 'Blueste', 'Pave']]

** Is it fast? **

No if we have to parse the file everytime and no index/dictionary/hashmap to find the records quickly.

## Service 2: Learn and Store Parameter

We want to use linear regression to predict house price based on lot area, year sold

In [6]:
import os
os.remove('model1.txt')

In [7]:
import numpy as np
from sklearn.linear_model import LinearRegression


def train(neighborhood, modelFile):
    df = pd.read_csv(FILE_LOCATION, sep=',')
    
    X_train = []
    y_train = []
    for idx, house in df.iterrows():
        if house['Neighborhood'] == neighborhood:
            X_train.append([house['LotArea'], house['YrSold']])
            y_train.append(house['SalePrice'])
    X_train = np.array(X_train)
    y_train = np.array(y_train)
    model = LinearRegression()
    model.fit(X_train, y_train)
    f = open(modelFile, 'a')
    f.write( ','.join([neighborhood, str(model.coef_[0]), str(model.coef_[1]), str(model.intercept_) + '\n']))
    f.close()
    return model.coef_, model.intercept_

train('OldTown', 'model1.txt')
train('ClearCr', 'model1.txt')

(array([8.92693417e-01, 7.60214636e+03]), -15078478.009327307)

In [8]:
f = open('model1.txt')
print(f.readlines())
f.close()

['OldTown,9.999908577139136,-756.5748650874622,1565197.0723577144\n', 'ClearCr,0.8926934169569567,7602.146359807243,-15078478.009327307\n']


## Service 3: Prediction

In [9]:
TEST_FILE_LOCATION = 'test.csv'

In [10]:
def predict(neighborhood, modelFile):
    df = pd.read_csv(TEST_FILE_LOCATION, sep=',')
    
    X_pred = []
    for idx, house in df.iterrows():
        if house['Neighborhood'] == neighborhood:
            X_pred.append([house['LotArea'], house['YrSold']])
    X_pred = np.array(X_pred)
    model = LinearRegression()
    
    save_models = pd.read_csv(modelFile, header=None, sep=',').values
    for save_model in save_models:
        if save_model[0] == neighborhood:
            model.coef_ = np.array([save_model[1], save_model[2]])
            model.intercept_ = save_model[3]
    return model.predict(X_pred)

predict('OldTown', 'model1.txt')

array([ 92481.15470218,  89331.18350038, 102531.06282221, 113480.96271418,
       162990.51007959, 126870.84029896, 141040.71075277, 140480.71587245,
       134480.77072617, 134930.76661214, 150080.6281065 , 105681.03402401,
       125420.85355528, 173480.41417701,  75161.31304658,  99937.66831395,
       153237.18103011, 126697.42366638, 147537.23314114, 149337.21668502,
       117237.5101524 ,  99237.67471355, 153237.18103011, 153237.18103011,
        86037.79539173, 148307.22610158, 201836.736715  , 144237.26331068,
       109297.58274216, 121507.47111484, 146577.24191773, 105237.61985984,
       119277.49150214, 104487.62671655, 130437.38947423, 141237.29073754,
       129237.40044497,  81237.8392747 ,  78237.86670156,  99237.67471355,
       142437.27976679, 126177.42842037, 144517.26075084,  75237.89412842,
       102987.64042998, 103757.63339042, 147213.81787989, 121054.0570421 ,
        99994.24957864, 154353.75260397, 144353.84402683, 137833.90363454,
        93994.30443236,  

# Using database

In [11]:
import mysql.connector

mydb = mysql.connector.connect(
  host="52.37.193.91",
  port="3306",
  user="dbuser",
  passwd="dbuser789"
)

print(mydb)

## Service 1: Find some houses based on some criteria

In [12]:
mydb = mysql.connector.connect(
  host="52.37.193.91",
  port="3306",
  user="dbuser",
  passwd="dbuser789",
  database="housing"
)

def find_db(db, criterion):
    query = "SELECT Id, "
    query += ", ".join(criterion.keys())
    query += " FROM train WHERE "        
    for k, V in criterion.items():
        query += k + " = '" + V + "' AND "
    
    query += "1;"
    print("Sending query to database")
    print(query)
    
    mycursor = mydb.cursor()
    mycursor.execute(query)
    myresult = pd.DataFrame(mycursor.fetchall())
    
    return myresult

find_db(mydb, {'Neighborhood': 'Blueste', 'Street': 'Pave'})

Sending query to database
SELECT Id, Neighborhood, Street FROM train WHERE Neighborhood = 'Blueste' AND Street = 'Pave' AND 1;


0        1     2
0  600  Blueste  Pave
1  957  Blueste  Pave

## Service 2: Learn and Store Parameter

In [13]:
mydb = mysql.connector.connect(
  host="52.37.193.91",
  port="3306",
  user="dbuser",
  passwd="dbuser789",
  database="housing"
)

def train_db(neighborhood, db):
    query = "SELECT LotArea, YrSold, SalePrice FROM train WHERE Neighborhood = '" + neighborhood + "';"
    print(query)
    mycursor = db.cursor()
    mycursor.execute(query)
    myresult = mycursor.fetchall()
    X = np.array(myresult)  
    X_train = X[:, :-1]
    y_train = X[:, -1]
    
    query2 = "CREATE TABLE IF NOT EXISTS model (neighborhood VARCHAR(255), w1 FLOAT(20,5), w2 FLOAT(20, 5), b FLOAT(20, 5));"
    print(query2)
    mycursor.execute(query2)
    db.commit()
    
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    query3 = "INSERT INTO model VALUES ('" + neighborhood + "', " + str(model.coef_[0]) + ", " + str(model.coef_[1]) + ", " + str(model.intercept_) + ");"
    print(query3)
    mycursor.execute(query3)
    db.commit()
    return

train_db('OldTown', mydb)
train_db('ClearCr', mydb)

SELECT LotArea, YrSold, SalePrice FROM train WHERE Neighborhood = 'OldTown';
CREATE TABLE IF NOT EXISTS model (neighborhood VARCHAR(255), w1 FLOAT(20,5), w2 FLOAT(20, 5), b FLOAT(20, 5));
INSERT INTO model VALUES ('OldTown', 9.999908577139136, -756.5748650874622, 1565197.0723577144);
SELECT LotArea, YrSold, SalePrice FROM train WHERE Neighborhood = 'ClearCr';
CREATE TABLE IF NOT EXISTS model (neighborhood VARCHAR(255), w1 FLOAT(20,5), w2 FLOAT(20, 5), b FLOAT(20, 5));
INSERT INTO model VALUES ('ClearCr', 0.8926934169569567, 7602.146359807243, -15078478.009327307);


## Service 3: Prediction

In [14]:

def prediction_db(neighborhood, db):
    mycursor = db.cursor()
    mycursor.execute("SELECT * FROM model WHERE neighborhood = '" + neighborhood +"';")
    params = np.array(mycursor.fetchone())
    print(params)
    
    query2 = "SELECT LotArea, YrSold FROM test WHERE Neighborhood = '" + neighborhood + "';"
    print(query2)
    mycursor2 = db.cursor()
    mycursor2.execute(query2)
    myresult2 = mycursor2.fetchall()
    X_test = np.array(myresult2)  
    
    model = LinearRegression()
    model.coef_ = params[1:3].astype(float)
    model.intercept_ = params[3].astype(float)
    
    return model.predict(X_test)

prediction_db("OldTown", mydb)

['OldTown' '9.99991' '-756.57489' '1565197.125']
SELECT LotArea, YrSold FROM test WHERE Neighborhood = 'OldTown';


array([ 92481.1641 ,  89331.19245, 102531.07365, 113480.9751 ,
       162990.52951, 126870.85459, 141040.72706, 140480.7321 ,
       134480.7861 , 134930.78205, 150080.6457 , 105681.0453 ,
       125420.86764, 173480.4351 ,  75161.31998,  99937.67869,
       153237.19899, 126697.43785, 147537.25029, 149337.23409,
       117237.52299,  99237.68499, 153237.19899, 153237.19899,
        86037.80379, 148307.24336, 201836.76159, 144237.27999,
       109297.59445, 121507.48456, 146577.25893, 105237.63099,
       119277.50463, 104487.63774, 130437.40419, 141237.30699,
       129237.41499,  81237.84699,  78237.87399,  99237.68499,
       142437.29619, 126177.44253, 144517.27747,  75237.90099,
       102987.65124, 103757.64431, 147213.8349 , 121054.07034,
        99994.25988, 154353.77064, 144353.86064, 137833.91932,
        93994.31388,  93994.31388, 105994.20588, 160253.71754,
       122274.05936, 119074.08816,  99994.25988, 153993.77388,
       113554.13784, 105134.21362, 135993.93588, 119104