# Amphi 6 - Regression [1] - Linear Regression, Polynomial Regression, Ridge and Lasso

# 1. Linear Regression

In regression problem, we would like to predict values of a variable $y$ as a function of some variable $\mathbf X \in \mathbf R^D$. 

Let $\mathbf X_1, \ldots, \mathbf X_N$ and $y_1, \ldots, y_N$ be some observations of $\mathbf X$ and $y$, respectively. We want to define a function $g(\mathbf X)$ to describe the relation between $y$ and $g(\mathbf X)$, hopefully $y \approx g(\mathbf X)$. 

## 1.1 The loss function

We define a **loss function** $L(g, \mathbf X, y)$ which has small value when $f(\mathbf X) \approx y$ and greater value when $f(\mathbf X)$ is far from $y$.  

In regression, one of the most common choices is the **square loss**. It is convenient for differentiation calculus.

**Quadratic loss (with respect to the estimation of $y$ by $g(\mathbf X)$**
$$ L(g, \mathbf X, y) = \vert y - g(\mathbf X) \vert^2 $$

Suppose that $g(\mathbf X)$ is a good prediction of $y$, then $g(\mathbf X_i) \approx y_i$ for $N$ observations $(\mathbf X_i, y_i), i = 1, \ldots, N$. In practice, we can define the loss with respect to the estimation of $y_1, \ldots, y_N$ by $g(\mathbf X_1), \ldots, g(\mathbf X_N)$ as the sum of square loss on each observation.

**Quadratic loss (for $ N $ observations)**
$$ L(g, \mathbf X_1, \ldots, \mathbf X_N, y_1, \ldots, y_N) = \sum_{n=1}^N \vert y_n - g(\mathbf X_n) \vert^2 $$

This loss is also called the squared error/squared loss function.
Its mean $$\frac1N L(g, \mathbf X_1, \ldots, \mathbf X_N, y_1, \ldots, y_N) $$ is called the **mean-squared error**.
Its square root $$\sqrt {\frac1N L(g, \mathbf X_1, \ldots, \mathbf X_N, y_1, \ldots, y_N) }$$ is called the **root-mean-squared error** (RMSE).

## 1.2 Linear model

In regression, the model is called linear if $g(\mathbf X)$ is of the form:
$$
g(\mathbf X) = \mathbf X \cdot \mathbf w + b
$$
where $\mathbf w \in \mathbf R^D$, $\mathbf b \in \mathbf R$.

By adding a new coordinate to variable $\mathbf X$ if necessary, we can suppose that the last coordinate of $\mathbf X$ is always 1. Then the linear model have the form:
$$
g(\mathbf X) = \mathbf X \cdot \mathbf w
$$
Here $b$ in the first representation become the last coordinate of $\mathbf w$.

Hence, without loss of generality, we will use $g(\mathbf X) = \mathbf X \cdot \mathbf w$ as the general form of linear models.

## 1.3 Minimizing the loss function

If we choose the square loss as our loss function (a criterion to evaluate which model is better), linear model as our model, and the observation $(\mathbf X_n, y_n)_{n = 1, \ldots, N}$ as training data, then the evident strategy is to find $\mathbf w$ that minimizes the loss function over the training data. The problems becomes:

$$
\max\limits_{\mathbf w \in \mathbf R^D} \sum_{n=1}^N \vert y_n - \mathbf X_n \cdot \mathbf w \vert^2
$$

Let $\mathbf y = (y_1, \ldots, y_N)^t$ denote the vector in $\mathbf R^N$ whose coordinates are the $N$ observations of $y$, and $\mathbf \Phi$ denote the matrix in $\mathbf R^{N \times D}$ whose rows are $\mathbf X_n^t$, the $N$ observations of $X$.

Then $\sum_{n=1}^N \vert y_n - \mathbf X_n \cdot \mathbf w \vert^2$ becomes $\Vert \mathbf y - \mathbf \Phi \mathbf w \Vert^2$. The problem becomes:

$$
\max\limits_{\mathbf w \in \mathbf R^D} \Vert \mathbf y - \mathbf \Phi \mathbf w \Vert^2
$$

Let $\mathcal L(\mathbf w) = \Vert \mathbf y - \mathbf \Phi \cdot \mathbf w \Vert^2$. This is a function $\mathbf R^D \to \mathbf R$, convex in $\mathbf w$, hence a local minimum (if exists) will be unique and minimize the function.

The minimum can be found by solving:
$$
\nabla_{\mathbf w} \mathcal L = \mathbf 0 \Leftrightarrow 2\mathbf \Phi^t(\mathbf \Phi \mathbf w - \mathbf y) = 0
$$
$$
\Leftrightarrow \mathbf \Phi^t \mathbf \Phi \mathbf w = \mathbf \Phi^t \mathbf y
$$

In case $\mathbf \Phi^t \mathbf \Phi$ invertible, the solution is
$$
\hat{\mathbf w} = (\mathbf \Phi^t \mathbf \Phi)^{-1} \mathbf \Phi^t \mathbf y
$$

If $\Phi^t\Phi$ is not invertible, the inverse can be replace by the (Moore-Penrose) pseudo inverse matrix or any generalized pseudo inverse.
$$
\hat{ \mathbf w} = (\mathbf \Phi^t \mathbf \Phi)^{+} \mathbf \Phi^t \mathbf y
$$

## 1.4 The Moore-Penrose pseudo inverse matrix in Python

Use **numpy.linalg.pinv** to find the pseudo inverse.

In [34]:
import numpy as np
X = np.array([[1, 1, 1], [1, 2, 3]])
y = np.array([2, 3])
print X.transpose().dot(X) 

[[ 2  3  4]
 [ 3  5  7]
 [ 4  7 10]]


In [35]:
#np.linalg.inv(X.transpose().dot(X) )

In [36]:
print np.linalg.pinv(X.transpose().dot(X))

[[ 2.02777778  0.44444444 -1.13888889]
 [ 0.44444444  0.11111111 -0.22222222]
 [-1.13888889 -0.22222222  0.69444444]]


In [39]:
w = np.linalg.pinv(X.transpose().dot(X)).dot(X.transpose()).dot(y)
print w

[ 1.16666667  0.66666667  0.16666667]


In [40]:
print (X.transpose().dot(X)).dot(w) #Phi^t Phi w

[  5.   8.  11.]


In [42]:
print (X.transpose().dot(y)) #Phi^t y

[ 5  8 11]


## 1.5 Complexity

The solution in closed form can be found in $O(ND^2)$ (case $D << N$) or $O(D^3)$ (case $N << D$).

# 2 Probabilistic Model for Linear Regression

## 2.1 Hypothesis

Suppose that the random variable $\mathbf X \in \mathbf R^D$ and the random variable $y$ satisfying:

- The distribution of $\mathbf X$ is arbitrary.
- 
$$
y|\mathbf X \sim \mathcal N \left(\mathbf X \cdot \mathbf w, \sigma \right) 
$$

for some unknown vector $\mathbf w$. Equivalently,

$$
p(y | \mathbf X) = \frac1{\sqrt{2\pi}\sigma} \exp\left( -\frac{|y - \mathbf X \cdot \mathbf w|^2}{2\sigma^2}\right)
$$

Or equivalently,
$$
y = \mathbf X \cdot \mathbf w + \epsilon
$$
where $\epsilon$ is some white noise ($\epsilon \sim \mathcal N(0, \sigma)$), independent of $\mathbf X$ and independent across observations.

## 2.2 Likelihood function

Consequence of assumption: $y$ is independent across observations, conditional on $\mathbf X$, i.e., if $(\mathbf X_i, y_i)$, $(\mathbf X_j, y_j)$ are observations of $(\mathbf X, y)$, then

$$
p(y_i, y_j | \mathbf X_i, \mathbf X_j) = p(y_i| \mathbf X_i)p(y_j | \mathbf X_j)
$$

Given $N$ observations of $\mathbf X, y$ as observations of $N$ iid variables following the same rule as $(\mathbf X, y)$. Then:
$$
p(y_1, \ldots, y_N | \mathbf X_1, \ldots, \mathbf X_N) = p(y_1| \mathbf X_1) \ldots p(y_N | \mathbf X_N) 
$$

This is a function of $\mathbf w, \sigma$; is called the likelihood function of observing the data:

$$
p(y_1, \ldots, y_N | \mathbf X_1, \ldots, \mathbf X_N; \mathbf w, \sigma) = \prod_{n=1}^N \frac{1}{\sqrt{2\pi}\sigma} \exp \left(-\frac{|y_n - \mathbf X_n \cdot \mathbf w|^2}{2\sigma^2} \right) = (2\pi)^{-N/2} \sigma^{-N} \exp\left( - \sum_{n=1}^N \frac{|y_n - \mathbf X_n \cdot \mathbf w|^2}{2\sigma^2} \right)
$$

The probabilistic model of linear regression aims to maximize this function with respect to $\mathbf w, \sigma$. Equivalently, we minimize the negative **log-likelihood**:

$$
L(\mathbf w, \sigma) = -\frac N{2} \log 2\pi - N \log \sigma - \frac 1 {2\sigma^2} \sum_{n=1}^N |y_n - \mathbf X_n \cdot \mathbf w|^2
$$

## 2.3 The estimators

The solution of the minimization problem can be found by deriving the function $L$ wrt $\mathbf w$, $\mathbf \sigma$. This is a convex function in $\mathbf w$.
$$
\hat{\mathbf w} = (\mathbf \Phi^t \mathbf \Phi)^{-1} \mathbf \Phi^t \mathbf y
$$

$$
\hat \sigma^2 = \frac1N \sum_{n=1}^N \left( y_n - \mathbf X_n \cdot \hat{\mathbf w} \right)^2 = \frac1N \Vert \mathbf y - \mathbf \Phi \hat{\mathbf w} \Vert^2
$$

The estimator $\hat {\mathbf w}$ is unbiased: $\mathbf E[\hat{\mathbf w}] = \mathbf w$.

The estimator $\hat {\sigma}$ is biased: $\mathbf E [\hat {\sigma}^2] = \frac{N-D}{N} \sigma^2$. When $\mathbf E [\hat {\sigma}^2] < \sigma^2$, we say that the $\sigma$ is underestimated. We can use $\frac{N}{N-D}\hat{\sigma}$ as an unbiased estimator for $\sigma$.

# 3. Implementation of Linear Regression in scikit-learn

In scikit learn, linear regression model is implemented by **`LinearRegression`** class.

http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

**Parameters:**
- `fit_intercept`: `True` when the intercept (coefficient of degree 0 is 0)
- `normalize`: `True` if we want to normalize the columns

**Attributes:**
- `coef_`
- `intercept_`

**Methods:**
- `fit`
- `predict`
- `score`: The R2-score (Coefficient of determination) evaluated on test set.

**Remind**:
R2-score: https://fr.wikipedia.org/wiki/Coefficient_de_d%C3%A9termination

### Example:

We simulate a case $y = \mathbf X \cdot \mathbf w + b + \epsilon$ where $\epsilon$ is a white noise (some Gaussian distribution of mean 0 and variance $\sigma^2 = 0.01$).

In [10]:
import numpy as np
np.random.seed(0)
from sklearn.linear_model import LinearRegression

TEST_SIZE = 0.2
TRAIN_TEST_SPLIT_RANDOM_STATE = 0

w = np.array([1.5, -2.1, 4, 0, -1.3])
b = 2
sigma = 0.1

D = 5
N = 10000

X = np.random.uniform(-5, 5, [N, D])
epsilon = np.random.normal(0, sigma, N)
y = X.dot(w) + b + epsilon


lr_model = LinearRegression()
lr_model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

We retrieved the coefficients

In [11]:
lr_model.coef_, lr_model.intercept_

(array([ 1.49938033e+00, -2.09964527e+00,  4.00031001e+00,  7.13504117e-04,
        -1.30053577e+00]), 1.999665613542589)

The approximation

In [12]:
y_pred = lr_model.predict(X)
import pandas as pd
pd.DataFrame([y, y_pred])

0          1          2          3         4          5         6     \
0  3.277741  22.668349  13.986498  14.465190  6.347043  30.614259 -2.897176   
1  3.317423  22.688948  14.070902  14.378545  6.320241  30.484073 -2.783799   

       7         8         9       ...           9990       9991       9992  \
0  3.712321  6.841166 -2.561723    ...      15.815272   9.788053  13.152335   
1  3.726107  6.949122 -2.433810    ...      15.687191  10.004899  13.247911   

        9993      9994      9995       9996     9997      9998       9999  
0  17.614369 -4.396698 -6.814206  18.662390 -1.90517 -1.540044 -12.746520  
1  17.633092 -4.367921 -6.652553  18.685393 -1.88928 -1.591966 -12.683399  

[2 rows x 10000 columns]

**R2-score**

In [13]:
lr_model.score(X, y)

0.999951318606377

**RMSE**

In [14]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y, y_pred))

0.09976205156094636

# 4. Train/Test Split and Cross Validation

# 5. Polynomial Regression

# 6. The Bias-Variance Trade-off

# 7. Feature Selection

# 8. Ridge and Lasso

[1] http://www.stat.cmu.edu/~cshalizi/mreg/15/lectures/06/lecture-06.pdf